# For development purposes only - do not use in production
version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  api1:
    image: node:12.10.0-alpine
    command: node /app/index.js
    environment:
      INSTANCE_ID : 1
      API_PORT : 5555
      REDIS_HOST : redis
      REDIS_PORT : 6379
    ports:
      - "5555:5555"
    volumes:
      - ./:/app
  api2:
    image: node:12.10.0-alpine
    command: node /app/index.js
    environment:
      INSTANCE_ID : 2
      API_PORT : 5556
      REDIS_HOST : redis
      REDIS_PORT : 6379
    ports:
      - "5556:5556"
    volumes:
      - ./:/app

